### ISSUE TITLE
Request for model checkpoints

### ISSUE THREAD

**Issue by yashika-git** [joos2010kj/CLIP-TSA#3]
Hello,

Thanks for the code.
Could you please upload the model's checkpoints?

**Comment by joos2010kj** [comment]
Hi,

Unfortunately, I no longer have access to the server, and I think all the data including checkpoints have been all purged, but the next time I have time to run them, I will share them here (FYI: should take ~5 hours combined to get the best checkpoints for all three datasets)

**Comment by yashika-git** [comment]
Thanks for the reply.
Would really appreciate you sharing them!
I tried training the model on the UCF Crime dataset, but was getting OOM errors even on using 4 GPUs, each having approx 24 GBs VRAM, so unfortunately, only managed to generate the checkpoints without the TSA module.

**Comment by joos2010kj** [comment]
As far as I remember, UCF Crime required the most memory among the three to get the best performance given its highest value of k & large dataset size.  You can always adjust the k value (https://github.com/joos2010kj/CLIP-TSA/blob/main/runner.sh) to a lower value if OOM error keeps happening, although you may not be able to yield the reported best performance.  One thing assured is, they are all runnable independently with a single RTX8000 GPU as I never had a problem with OOM issue back when I ran experiments at the institution and the clusters provided used RTX8000.

**Comment by yashika-git** [comment]
I see, thanks. For my evaluations, I want to generate the checkpoints using the settings that yielded the best performance. Unfortunately, we don't have RTX8000 clusters at our institution.

**Comment by joos2010kj** [comment]
Sorry to hear that.  Again, unfortunately, I do not have access to the clusters as I am no longer affiliated with the institution because it was my summer internship.  I will try to get the checkpoints when the opportunity comes by.

**Comment by joos2010kj** [comment]
If it helps:

ShanghaiTech Campus Checkpoint (98.49%): https://drive.google.com/file/d/1enEAkoul3YsaAQ-SXuPH3q-sJq5pkNwr/view?usp=sharing

UCF-Crime Checkpoint (87.55%): https://drive.google.com/file/d/1uBi2KeJG5JkmpYrKKtRnbh_5JNY8Psp3/view?usp=sharing

XD-Violence Checkpoint (80.67%): https://drive.google.com/file/d/1UtNGP5QKI2zftJnVh_VzyDsfTdCVISsd/view?usp=sharing

As you may have noticed, the checkpoints' performances do not match what is reported on the paper because, when I reported the performance on the paper, I ran each with five different seeds and averaged them out.  Again, I don't have those checkpoints anymore because my system has been wiped out -- sorry about that.

However, I managed to borrow the cluster for a very limited amount of time after this request was raised for those without enough resources.  Keep in mind, I wasn't able to get the same scores here because I was able to run for only a limited amount of time. For instance, the ShanghaiTech Campus Checkpoint yielded a score of 0.9849, which is higher than the reported 0.9832, while UCF-Crime and XD-Violence yielded lower scores.  But if run on multiple seeds iteratively and averaged out, you will be able to get very close scores to what has been reported.

**Comment by yashika-git** [comment]
Thank you, this is definitely helpful.
Yes, I understand that the seed values can result in these variations.
Thanks again.
