### ISSUE TITLE
Congrats on the nice work!

### ISSUE THREAD

**Issue by wyzjack** [joos2010kj/CLIP-TSA#5]
Congrats on the nice work!

I have a small question on the extracted CLIP features. It seems that in your provided CLIP features, the testing set of UCF Crime dataset is not complete? Could you provide the complete version? Thanks so much.

<img width="308" alt="image" src="https://github.com/joos2010kj/CLIP-TSA/assets/36599296/701aebb4-77b0-4908-b7f1-911e80508235">

I would appreciate it very much if you could reply.

**Comment by joos2010kj** [comment]
Hello @wyzjack,

I'm not following what you mean -- AFAIK, those two samples (Abuse028, 030) are the only testing samples for "ABUSE" category provided by UCF Crime dataset.

You can also follow the works by other people, who also have just those two samples as well: https://stuxidianeducn-my.sharepoint.com/personal/pengwu_stu_xidian_edu_cn/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2Fpengwu%5Fstu%5Fxidian%5Fedu%5Fcn%2FDocuments%2FUCF%2DCrime%2FI3D%2FTest%2FRGB%2FAbuse

If your question is about why it has 1 for each rather than 10 for each, then it's because we did not employ 10-crop technique (https://pytorch.org/vision/main/generated/torchvision.transforms.TenCrop.html), which is a form of augmentation technique that some of the other VAD papers also employed when I surveyed papers at the time.

Thanks.

**Comment by wyzjack** [comment]
Got it, thanks so much!
