### ISSUE TITLE
About FAQ Q1

### ISSUE THREAD

**Issue by zg-young** [joos2010kj/CLIP-TSA#8]
It seems that there are several places other than `generator = torch.Generator()` that need to be modified in order to run smoothly.
![image](https://github.com/user-attachments/assets/fb4158a3-3b78-44d9-aec3-05e92537328a)

**Comment by joos2010kj** [comment]
Hmm, that's interesting to hear because I haven't had an issue with other lines of the file than what I mentioned when run in three-ish different environments.  But anyhow, if this route solved the problem, thanks for bringing them to my attention, which should help those who also may encounter a similar problem.
